# Generated by Django 5.1.8 on 2025-09-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_classified', '0003_auto_20180717_1107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Messaggio opzionale per la proposta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Scadenza automatica proposta', null=True)),
                ('is_counter_offer', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('sent', 'Inviata'), ('accepted', 'Accettata'), ('declined', 'Rifiutata'), ('cancelled', 'Annullata'), ('completed', 'Completata')], default='sent', max_length=20)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL)),
                ('offer_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_offers', to='django_classified.item')),
                ('parent_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.tradeproposal')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL)),
                ('want_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_targets', to='django_classified.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Messaggio per organizzare lo scambio', max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Immagine allegata al messaggio', null=True, upload_to='trade_messages/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_messages', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trade.tradeproposal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], help_text='Valutazione da 1 a 5 stelle')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='trade.tradeproposal')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Numero di telefono per contatti diretti negli scambi', max_length=20, null=True, verbose_name='Numero di Telefono')),
                ('show_phone_in_trades', models.BooleanField(default=False, help_text='Permetti di mostrare il tuo numero agli altri utenti negli scambi accettati', verbose_name='Mostra telefono negli scambi')),
                ('location', models.CharField(blank=True, help_text='La tua zona per facilitare gli incontri', max_length=100, null=True, verbose_name='Città/Zona')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_profile_extended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utente',
            },
        ),
        migrations.CreateModel(
            name='UserTradeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades_completed', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, help_text='Numero di telefono per organizzare scambi', max_length=20)),
                ('show_phone_in_trades', models.BooleanField(default=False, help_text='Mostra il numero negli scambi accettati')),
                ('location', models.CharField(blank=True, help_text='Città o zona di preferenza per gli scambi', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Breve descrizione del profilo', max_length=500)),
                ('auto_accept_counters', models.BooleanField(default=False, help_text='Accetta automaticamente le contro-proposte')),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_verified_trader', models.BooleanField(default=False)),
                ('join_trade_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['to_user', 'state'], name='trade_trade_to_user_46e5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['from_user', 'state'], name='trade_trade_from_us_c8ba4a_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['created_at'], name='trade_trade_created_a17b06_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['expires_at'], name='trade_trade_expires_5ba952_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradeproposal',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='tp_users_distinct'),
        ),
        migrations.AddConstraint(
            model_name='tradeproposal',
            constraint=models.CheckConstraint(condition=models.Q(('offer_item', models.F('want_item')), _negated=True), name='tp_items_distinct'),
        ),
        migrations.AddIndex(
            model_name='trademessage',
            index=models.Index(fields=['trade', 'created_at'], name='trade_trade_trade_i_9c4583_idx'),
        ),
        migrations.AddIndex(
            model_name='trademessage',
            index=models.Index(fields=['sender', 'created_at'], name='trade_trade_sender__3279fa_idx'),
        ),
        migrations.AddIndex(
            model_name='trademessage',
            index=models.Index(fields=['recipient', 'is_read'], name='trade_trade_recipie_b5187c_idx'),
        ),
        migrations.AddIndex(
            model_name='tradefeedback',
            index=models.Index(fields=['ratee', 'rating'], name='trade_trade_ratee_i_6d2c90_idx'),
        ),
        migrations.AddIndex(
            model_name='tradefeedback',
            index=models.Index(fields=['created_at'], name='trade_trade_created_981c3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradefeedback',
            unique_together={('trade', 'rater')},
        ),
    ]
