# Generated by Django 5.1.8 on 2025-08-31 11:20

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_classified', '0004_alter_area_options_alter_section_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', django_fsm.FSMField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='sent', max_length=50, protected=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL)),
                ('offer_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_offers', to='django_classified.item')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received', to=settings.AUTH_USER_MODEL)),
                ('want_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_targets', to='django_classified.item')),
            ],
        ),
        migrations.CreateModel(
            name='TradeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='trade.tradeproposal')),
            ],
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['to_user', 'state'], name='trade_trade_to_user_46e5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['from_user', 'state'], name='trade_trade_from_us_c8ba4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradeproposal',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='tp_users_distinct'),
        ),
        migrations.AddConstraint(
            model_name='tradeproposal',
            constraint=models.CheckConstraint(condition=models.Q(('offer_item', models.F('want_item')), _negated=True), name='tp_items_distinct'),
        ),
    ]
