# Generated by Django 5.1.8 on 2025-09-01 08:59

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_classified', '0004_alter_area_options_alter_section_options_and_more'),
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades_completed', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('auto_accept_counters', models.BooleanField(default=False, help_text='Accetta automaticamente le contro-proposte')),
                ('email_notifications', models.BooleanField(default=True)),
                ('is_verified_trader', models.BooleanField(default=False)),
                ('join_trade_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tradeproposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Scadenza automatica proposta', null=True),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='is_counter_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='parent_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.tradeproposal'),
        ),
        migrations.AddField(
            model_name='tradeproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tradefeedback',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tradefeedback',
            name='ratee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradefeedback',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradefeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], help_text='Valutazione da 1 a 5 stelle'),
        ),
        migrations.AlterField(
            model_name='tradefeedback',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='trade.tradeproposal'),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='message',
            field=models.TextField(blank=True, help_text='Messaggio opzionale per la proposta'),
        ),
        migrations.AlterField(
            model_name='tradeproposal',
            name='state',
            field=django_fsm.FSMField(choices=[('sent', 'Inviata'), ('accepted', 'Accettata'), ('declined', 'Rifiutata'), ('cancelled', 'Annullata'), ('completed', 'Completata')], default='sent', max_length=50, protected=True),
        ),
        migrations.AlterUniqueTogether(
            name='tradefeedback',
            unique_together={('trade', 'rater')},
        ),
        migrations.AddIndex(
            model_name='tradefeedback',
            index=models.Index(fields=['ratee', 'rating'], name='trade_trade_ratee_i_6d2c90_idx'),
        ),
        migrations.AddIndex(
            model_name='tradefeedback',
            index=models.Index(fields=['created_at'], name='trade_trade_created_981c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['created_at'], name='trade_trade_created_a17b06_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeproposal',
            index=models.Index(fields=['expires_at'], name='trade_trade_expires_5ba952_idx'),
        ),
        migrations.AddField(
            model_name='usertradeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
