# Generated by Django 5.1.8 on 2025-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_usertradeprofile_alter_tradeproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeproposal',
            name='state',
            field=models.CharField(choices=[('sent', 'Inviata'), ('accepted', 'Accettata'), ('declined', 'Rifiutata'), ('cancelled', 'Annullata'), ('completed', 'Completata')], default='sent', max_length=20),
        ),
    ]
