# Generated by Django 5.1.8 on 2025-09-01 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_tradeproposal_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Messaggio per organizzare lo scambio', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_messages', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trade.tradeproposal')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trade', 'created_at'], name='trade_trade_trade_i_9c4583_idx'), models.Index(fields=['recipient', 'is_read'], name='trade_trade_recipie_b5187c_idx')],
            },
        ),
    ]
