# Generated by Django 5.1.8 on 2025-09-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_userprofile'),
        ('trade', '0004_trademessage'),
    ]

    operations = [
    ]
